@baseUrl=https://localhost:5149


###
PUT {{baseUrl}}/api/cabins/73
Content-Type: application/json

{
    "name": "Updated Cabin Name"
}


### test oada
GET {{baseUrl}}/odata/cabins
Content-Type: application/json





### test oada
GET {{baseUrl}}/odata/cabins?$count=true&$top=2
Content-Type: application/json

