<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <!-- 身份认证相关 -->
        <PackageVersion Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
        <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
        <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
        <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />

        <!-- File Storage -->
        <PackageVersion Include="AWSSDK.S3" Version="4.0.19.1" />
        <PackageVersion Include="AWSSDK.Core" Version="4.0.3.21" />
        <PackageVersion Include="Microsoft.AspNetCore.StaticFiles" Version="2.3.9" />


        <!-- EF Core 统一 10.0.1 -->
        <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.1" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1" />
        <!-- Npgsql -->
        <PackageVersion Include="Npgsql" Version="10.0.1" />
        <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
        <!-- 其它公共包 -->
        <PackageVersion Include="FluentResults" Version="4.0.0" />
        <PackageVersion Include="Mapster" Version="7.4.0" />
        <!-- <PackageVersion Include="Scrutor" Version="6.1.0"/> -->
        <!-- <PackageVersion Include="Swashbuckle.AspNetCore" Version="9.0.5"/> -->
        <!-- <PackageVersion Include="MediatR" Version="12.5.0"/> -->
        <PackageVersion Include="FluentValidation" Version="12.0.0" />
        <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
        <PackageVersion Include="Microsoft.AspNetCore.OData" Version="9.4.1" />
    </ItemGroup>
</Project>